### ISSUE TITLE
monitorWrite() bug?

### ISSUE THREAD

**Issue by jackliang086** [Polidea/RxBluetoothKit#104]
when i subscribe monitorWrite() ,everytime i get Characteristic.value is always nil. why? thanks

**Comment by Kacper20** [comment]
What happened when you're doing 2 things instead:
Subscribe `monitorWrite` and once that fires `Next` trigger `read` on Characteristic. This should do what you intended.

Regards,
Kacper

**Comment by jackliang086** [comment]
there is the code snippet:

characteristic.monitorWrite()
            .subscribe(onNext: {[weak self] (c:Characteristic) in
                
                print(c.value) // <- the c.value is always nil

            }).addDisposableTo(disposeBag)

my intention is that i wanted to get the feedback after i write value to a characteristic

thanks!!!

**Comment by Kacper20** [comment]
@jackliang086 
Exactly, I suggest to do another operation in sequence:
```
characteristic.monitorWrite()
.flatMap { $0.readValue }
.subscribe(onNext: {
    print($0.value)
}.addDisposableTo(disposeBag)
```

Please let me know how it works for you :)

**Comment by jackliang086** [comment]
let me try,wait a seconds^_^

**Comment by jackliang086** [comment]
it works , but the read value is not what i writed T.T

**Comment by Kacper20** [comment]
That's weird. Are you writing this value from outside, or within your app from another place?

**Comment by jackliang086** [comment]
i just write the value one place ,
actually,i found this problem even if i only use corebluetooth framework. the value from the write value callback function is different to what i writing

**Comment by Kacper20** [comment]
It may be a problem with your firmware internals if that's the case.

**Comment by jackliang086** [comment]
yeah , i have the same idea

**Comment by jackliang086** [comment]
but i test it by the android platform,it is perfect.-_-

**Comment by Kacper20** [comment]
Are you using notifications or indications on Android? How does it work there exactly? I could ask some Android friends that are taking care of https://github.com/Polidea/RxAndroidBle library and maybe we'll come up with something.

Regards,

**Comment by jackliang086** [comment]
yes. but i do not think is the key place. my intention is easy, just test the callback value from the writed callback function on android platfrom. and everything is prefect.do you think there are some bugs on corebluetooth framework.because your library is base on corebluetooth framework

**Comment by Kacper20** [comment]
Could you tell me exactly what API and function calls are you using on Android?

**Comment by jackliang086** [comment]
public void onCharacteristicWrite(BluetoothGatt gatt, BluetoothGattCharacteristic characteristic, int status)

**Comment by jackliang086** [comment]
thanks a lot for your patience ^_^

**Comment by Kacper20** [comment]
@jackliang086 Could you tell me how are you writing value? I suspect that you're using `withoutResponse`. Could you try using `withResponse` and check the results?

**Comment by jackliang086** [comment]
no, i am using withResponse

c!.writeValue(data, type: CBCharacteristicWriteType.withResponse)

**Comment by Kacper20** [comment]
Hello @jackliang086 

Any updates on this?

**Comment by Kacper20** [comment]
I'm closing this as of now. If you have any other questions - please feel free to reopen issue, or open another one.

Kacper
