### ISSUE TITLE
Act on disconnect or bluetooth state changes

### ISSUE THREAD

**Issue by huguesbr** [Polidea/RxBluetoothKit#105]
Hi,

Thanks for this awesome work.

I'm having some trouble to find a way to correctly restore my device connection if any disconnect or bluetooth state trigger an error.

It's probably due to my skill level in Rx but I would love your insights.

I'm trying to create a `Device` object which will wrap the logic of waiting for correct BLE state, scan for peripheral, connect to one with specific name, detect services & characteristics, listen to some notification and then republish the notification using some PublishSubject to be consume by my controller (or what ever else).

The issues is that I would like to reconnect all of this if any error occurs (like device disconnection, ble state changes, ...).

This code have some trivial issues, like subscribing twice to the `characteristics`, but I can figure out how to not do it, if I use  a simple `share` on `characteristics` and the `retry` on my notification it won't work.

I'm having trouble wrapping my head around this...

```
class Device {
    let measure = PublishSubject<Data>()
    let alert = PublishSubject<Data>()
    
    private let disposeBag = DisposeBag()
    
    init(name: String) {
        let manager = BluetoothManager(queue: .main)
        
        let queue = DispatchQueue(label: "fr.xdev.rxbluetoothkit.bluetooth")
        let scheduler = SerialDispatchQueueScheduler(queue: queue, internalSerialQueueName: "")
        
        let characteristics = manager.rx_state
            .filter { $0 == .poweredOn }
            .take(1)
            .flatMap { _ in manager.scanForPeripherals(withServices: [.common(.main)]) } // extension on CBUUID
            .filter { $0.peripheral.name == name }
            .take(1)
            .flatMap { $0.peripheral.connect() }
            .flatMap { $0.discoverServices([.common(.main)]) } // extension on CBUUID
            .flatMap { Observable.from($0) }
            .flatMap { $0.discoverCharacteristics([.common(.measure), .common(.protection)]) } // extension on CBUUID
            .flatMap { Observable.from($0) }
        
        characteristics
            .filter { $0.uuid.type == .measure } // extension on CBUUID
            .flatMap { $0.setNotificationAndMonitorUpdates() }
            .map { $0.value }
            .unwrap() // ignore nil value
            .retryWithDelay(5) // !!!: retry and resubscribe to the full chain on error
            .subscribe(onNext: { [unowned self] data in
                self.measure.onNext(data!)
            })
            .disposed(by: disposeBag)
        
        characteristics
            .filter { $0.uuid.type == .alert } // extension on CBUUID
            .flatMap { $0.setNotificationAndMonitorUpdates() }
            .map { $0.value }
            .unwrap() // ignore nil value
            .retryWithDelay(5) // !!!: retry and resubscribe to the full chain on error
            .subscribe(onNext: { [unowned self] data in
                self.alert.onNext(data!)
            })
            .disposed(by: disposeBag)
    }
}
```
Here is an extended version of this sample project: https://gist.github.com/huguesbr/41290240fad1a4de290dd3e81305ed96

Any advices of how to organize this?

Thanks

**Comment by huguesbr** [comment]
Ok, (I think) I have found the issue.

I added a custom observable which wrapped the scanning and discovering of the peripheral.

I can then chain my BLE request and subscribing to notification and safely retry all on error.

```
func scan(name: String) -> Observable<Peripheral> {
        return Observable.create { (observer) -> Disposable in
            var peripheral: Peripheral! = nil
            let manager = BluetoothManager(queue: .main)
            let disposable = manager
                .rx_state
                .filter { $0 == .poweredOn }
                .take(1)
                .flatMap { _ in manager.scanForPeripherals(withServices: [.common(.main)]) } // extension on CBUUID
                .filter { $0.peripheral.name == name }
                .take(1)
                .flatMap { $0.peripheral.connect() }
                .do(onNext: { peripheral = $0 })
                .flatMap { $0.discoverServices([.common(.main)]) } // extension on CBUUID
                .flatMap { Observable.from($0) }
                .flatMap { $0.discoverCharacteristics([.common(.measure), .common(.protection)]) } // extension on CBUUID
                .flatMap { Observable.from($0) }
                .subscribe(
                    onError: {
                        observer.onError($0)
                },
                    onCompleted: {
                        observer.on(.next(peripheral))
                        observer.on(.completed)
                })
            return Disposables.create([disposable])
        }
    }
```

**Comment by Kacper20** [comment]
Hello @huguesbr 

Sorry about delay - will read the code today and try to advise you on something if I can.

Regards,

**Comment by huguesbr** [comment]
@Kacper20 no stress, already I can't thank you enough for this repo :)

**Comment by dimohamdy** [comment]
@huguesbr  I have this problem can you help me ?

**Comment by dimohamdy** [comment]
@huguesbr  how can i use your code to detect the connected peripheral is turn off

**Comment by huguesbr** [comment]
@dimohamdy yep. it's not optimized yet (it doesn't use saved peripherals feature from iOS) but basically I've split the discovering (scanning, connecting, discovering of services/characteristics) from the listening part. The discovering (scan function) return a peripheral Observable, if there is an error in the listening (it could also be on a read, ...), it retry this sequence...


I then use it like:

```
        scan(name: name)
            .flatMap { [unowned self] (peripheral: Peripheral) -> Observable<Peripheral> in
                // return an observable on reading some stuff from the device
            }
            .flatMap { [unowned self] (peripheral: Peripheral) -> Observable<Characteristic> in
                // return an observable on some characteristics (notification)
            }
            .retry() // retry the full sequence (scanning, ...) on any error
            .subscribe(onNext: {

            })
            .disposed(by: disposeBag)
```

**Comment by dimohamdy** [comment]
@huguesbr  i will try to apply this,thanks

**Comment by huguesbr** [comment]
@dimohamdy or I guess `manager.monitorDisconnection` is built for this..
@Kacper20 I saw the use of it in the example but just to display an alert, any sample of how to use it to restart the scanning? thx!

**Comment by huguesbr** [comment]
@Kacper20 let us know if you have some feedback.. I'm pretty sure I misunderstood something...

I would like to reach an implementation where my `Device` encapsulate all the BLE exchange / logic (scanning, connection, reconnecting, **iOS restoring**, **discovering services/characteristics**, *initial data exchange*) and re-expose the data via some `PublishSubject` (or `Variable`, simple `Observable`, what ever make sense). 

This exchange could be a **two** ways communication (in case of needing to send data to device).

Also, by *initial data exchange*, I mean a set of steps that needs to be perform on each connection to the device (sending some data, reading, ...).

Any good example of this or suggestions? 
The current sample project is fairly trivial in term of device relationship... (no complaint, still great works :P)

The protocol could look something like:
```
enum Status {
  case ...
}
protocol Device { 
  let aNotification: Observable<Data>
  let aWriteableThing: PublishSubject<Data>
  let status: Observable<Status>
  init(_ name: String) {}
}
```

Then in a controller for
```
let device = Device("BLEDevice")
device.aNotification.subscribe(onNext: { print($0) })
aButton.rx.tap { device.aWriteableThing.onNext(Data()) }
```

Step by step, I would love to be able to abstract a bit more `Device` to support passing it some `GATT`... 


Hope it make some sense, please feel free to bump me if unrelated with this project, but I think at the end that could make a nice addition...

Thank you

**Comment by Kacper20** [comment]
Hello @huguesbr 
Sorry for the delay - I was on vacations.
Tomorrow we have a meeting and will discuss this idea and lots of others.

Thank you for patience,

Kacper

**Comment by huguesbr** [comment]
Thank you for update @kacper20
Hope you got some good time off. 

Feel free to ask me for more info.

**Comment by Kacper20** [comment]
We've discussed your code a bit.
We're assuming that your intention is to have retry on the level of `Device`. This way it's impossible to be notified if any error occurs. 
Going further with your idea:
Looking at the first piece of code - you could simplify it a bit by using convenience methods on peripheral. Please read `Convenience Calling Methods` part of our `README.md`. It'll make your code better readable. 
We're thinking that doing `subscribe` calls in init is not particularly good practice. Calling constructor shouldn't be performing much logic besides constructing object, initialising properties etc.
It would be better to have a call to function like `start()`, which performs all of the logic. You have to ensure that `start` is called only once(or maybe just replace DisposeBag on beginning of the function).
`start` could return `Disposable`. This way when client of API is no longer interested in notifications and connection we could dispose resources to the system.

When you want to have writeable characteristic our advise is to expose just function call in interface. Internally it would use `PublishSubject`. Exposing it like you showed allows to error stream from the outside and it's not a good practice.

So protocol would look like:
```
protocol Device {
  let aNotification: Observable<Data>
  let status: Observable<Status>
  init(_ name: String) {}
  func start() -> Disposable
  func write(Data)
}
```

It's a good practice to make as little subscribe calls as possible and adjusting logic based on some enums or internal state.
To implement `write` you could internally use something like that(it doesn't compile but you should get the idea):
```swift
class ADevice {
    enum RequestType {
        case read
        case write(Data)
    }

    private let subject = PublishSubject<RequestType>()
    private let notifiedValues = PublishSubject<Data>()

    var aNotification: Observable<Data> {
        return notifiedValues
    }

    func start() -> Disposable {
        ... //Assuming that Characteristic is writeable and readable
        .flatMap { (characteristic: Characteristic) in
            return self.initializeCommunication(with: characteristic)
        }
        //We're switching now to requests when characteristic was fully initialized
        .flatMap { characteristic in
            return Observable.of(
                characteristic.setNotificationAndMonitorUpdates().map { $0.value },
                self.handleWriteRequests(with: characteristic)
                 ).merge() 
        }
        .subscribe(notifiedValues)
        //Disposable is received, should be returned from the start function
    }

    func handleRequest(with characteristic: Characteristic) -> Observable<Data> {
        return subject.flatMap { request in 
            switch request {
                case .read:
                    return characteristic.readValue().map { $0.value }
                case let .write(dataToWrite):
                    return characteristic.writeValue(dataToWrite).map { $0.value }
                //If you want to omit some values in aNotification you could flatMap one of observables to `Observable.empty()`
            }
        }
    }

    func initializeCommunication(with characteristic: Characteristic) {
        //Does some starting operations like writing initial values and so on...
    }

    func write(data: Data) {
        subject.onNext(.write(data))
    }
}
```

**Comment by huguesbr** [comment]
@Kacper20 @Cierpliwy , thx for the update.
Ok, I guess I missed that party your docs about `Convenience Calling Methods` (I was wondering why  you had some `readValue` directly on peripheral, I guess it make more sense now), thanks that will simplify my code.
Ok, for the moving the `subscription` part to `start` on which I return the `Disposable`, thx for pointing this out.
Ok for the `write` methods vs exposing `PublishSubect`, I actually already switch back to exposing methods, I agree it make more sense.
For the last part, I still need to read more you code... :)

**Comment by Kacper20** [comment]
No problem, feel free to ask any questions :)

**Comment by Kacper20** [comment]
Hello,

I'm closing this for now. Please feel free to re-open the issue or open another one :)

Regards,

Kacper

**Comment by huguesbr** [comment]
@Kacper20 👍 will let you know, thx
