### ISSUE TITLE
Getting scan response data

### ISSUE THREAD

**Issue by thierrybucco** [Polidea/RxBluetoothKit#112]
Hi,

I would like to receive scan response data, but It seems that manufacturerData is missing from scannedPeripheral.advertisementData.

Do you have an idea why?

Thanks

Thierry

**Comment by Kacper20** [comment]
Hi @thierrybucco 

Sorry for such a late response - I haven't noticed this issue earlier.
Advertising data is thing that is managed by the device by itself, so I believe the device is not advertising this information.
