### ISSUE TITLE
Is that possible to stopScan manually

### ISSUE THREAD

**Issue by dubiao** [Polidea/RxBluetoothKit#116]
I begin from 
> let manager = BluetoothManager(queue: .main);

and chain many operations to do.
I want to stop scan manually like I was using `CBCentralManager` do `manager.stopScan()` . 
I know use `take(1)` after `scanForPeripherals` can cause stopScan. But I want call the stop by manull. Any advice?
Thank you.

**Comment by Kacper20** [comment]
Hello,

When you're doing `subscribe` to scan `Observable` you're receiving `Disposable` instance. Just call `dispose` on it - scan will stop then.

Kacper

**Comment by dubiao** [comment]
It helps me. Thanks. Closing.
