### ISSUE TITLE
[5.0] Use `Single` RxSwift unit where possible

### ISSUE THREAD

**Issue by moogle19** [Polidea/RxBluetoothKit#120]
Since [RxSwift 3.3](https://github.com/ReactiveX/RxSwift/releases/tag/3.3.0) there is the `Single` type, which emit only one Element or an error. 
I think this should be use for everything that just emits one value, like `readValue` and `writeValue`.
Because it is a breaking change, it should probably be added in 4.0

**Comment by Kacper20** [comment]
That's a good idea.
We're in progress with 4.0 right now and we'll definitely use it.

Thanks!

**Comment by Kacper20** [comment]
Implemented as a part of #147 on `5.0-dev` branch
