### ISSUE TITLE
Version bump for core bluetooth access on disconnect fixes

### ISSUE THREAD

**Issue by RamblinWreck77** [Polidea/RxBluetoothKit#131]
Hello!

Would you guys mind doing a version bump so I don't have to point at the master branch for future releases to include the (resolved) Core Bluetooth state issue?

Thanks again for knocking this one out.

**Comment by Kacper20** [comment]
Hi!

Sorry for the lack of response - I was on vacations. I will merge today #129 and release a new version.

Regards,
Kacper

**Comment by Kacper20** [comment]
Hello @RamblinWreck77,

It's now ready in 3.1 version of the lib :)
Thanks for the feedback!

Kacper

**Comment by RamblinWreck77** [comment]
Hello! Can you push this update to cocoapods? Looks like the new version isn't available yet.

**Comment by Cierpliwy** [comment]
Hello! I have released 3.1 to cocoapods. Enjoy :)
