### ISSUE TITLE
 Send Data anyWhere

### ISSUE THREAD

**Issue by Xiahaiquan** [Polidea/RxBluetoothKit#133]
Hi 

    I  scanned  peripherals in my scanVC . then I want to send data to peripherals in other VC . how I can do . Like used on OC is singleton。so do ? or other way ?

Thank you

**Comment by Kacper20** [comment]
Hello @Xiahaiquan 

Could you please elaborate more on your problem? To be honest I'm having troubles understanding your problem. Are you using example app? Could you provide some code sample?

**Comment by Xiahaiquan** [comment]
OK ,        I mean is  I have a bluetoothManager in scanViewController. but I want use  the bluetoothManager  send data to peripherals at other ViewController . how can I do .              Thank you

**Comment by Kacper20** [comment]
Hi @Xiahaiquan,

One thing you need to do is to pass `BluetoothManager` to the other controllers in initializers and that should be enough. Then, they'll have access to the manager, too.

**Comment by Xiahaiquan** [comment]
OK @Kacper20 

I will try it.  Thank you

**Comment by Kacper20** [comment]
Hello @Xiahaiquan,

Any progress on this?

**Comment by Xiahaiquan** [comment]
@Kacper20 
   this has no more. Thank you
