### ISSUE TITLE
Does setNotificationAndMonitorUpdates work on macOS?

### ISSUE THREAD

**Issue by ctylim** [Polidea/RxBluetoothKit#134]
Hello, I have a problem with using `setNotificationAndMonitorUpdates` on **macOS**.
After connecting to peripheral and discovering services & characteristics (these process did work), I implemented 
```
// store discovered characteristics before this process
for characteristic in self.characteristics {
    characteristic.setNotificationAndMonitorUpdates()
        .observeOn(MainScheduler.instance)
        .subscribe(onNext: {        
            print("notified: \($0.value)")
        })
        .disposed(by: self.disposeBag)
}
```
I expected some notification messages appear in `.subscribe`, but this seems not worked.
Anything wrong or any similar problems on this? Here are my environments,

- macOS Sierra (10.12)
- Xcode 8.3.3
- Additional information: `Peripheral.setNotificationAndMonitorUpdates` also did not work.  `readValue` and `writeValue` worked fine.

Thank you in advance. Great project!

**Comment by ctylim** [comment]
Ah, I resolved it by myself.
I tried to notify characteristics which does not have "notify" property (needs to be filtered).
Sorry for bothering you.

**Comment by Kacper20** [comment]
Hi @ctylim,
Ahh, great! :-)
Happy to answer any other question.

Regards,

Kacper
