### ISSUE TITLE
How to scan for particular device type ?

### ISSUE THREAD

**Issue by varun-naharia** [Polidea/RxBluetoothKit#135]
How we can scan for particular ble device type 
https://www.bluetooth.com/specifications/gatt/services
by assigned number

**Comment by Kacper20** [comment]
Hi @varun-naharia,

Method scan takes an array of `CBUUID` instances. Just create this UUID with the service you need and `CoreBluetooth` will automatically perform filtering.

**Comment by Kacper20** [comment]
Closing for now. If I can make something more clear — please feel free to reopen the issue.
