### ISSUE TITLE
How can I receive data per 0.2sec?

### ISSUE THREAD

**Issue by rosebaek** [Polidea/RxBluetoothKit#137]
I'd like to receive the data when I want.
If it is possible, I want to receive ther data per 0.2 sec.

Kindly check and give me the feedback.

Many thanks,
Jangmi

**Comment by Kacper20** [comment]
Hi @rosebaek,

You cannot say that you want to receive new data from the device exactly per 0.2 sec. Actual response time from the device varies in time(based on the device speed itself, noise).

You could say that you want to execute read command every 0.2 sec and this could be done with `Observable.interval` operator.

**Comment by rosebaek** [comment]
I don't know Observable.interval....
I'm sorry that detailed tell to me

**Comment by Kacper20** [comment]
Here you could find the docs:
http://reactivex.io/documentation/operators/interval.html

Basically, you're giving it the time interval and it emits elements in given period after subscribe.
You could find some usages here: https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md

**Comment by Kacper20** [comment]
Hi, any progress on this?

**Comment by rosebaek** [comment]
no...I'm trying to solve this problem....
However,  I need to upgrade the rxBluetoothKit after installing ios11 and Xcode upgrade.

**Comment by Kacper20** [comment]
If you have any further questions — please feel free to reopen the issue.
