### ISSUE TITLE
carthage update fail for 3.1

### ISSUE THREAD

**Issue by zhentan** [Polidea/RxBluetoothKit#140]
I'm getting the following error when Carthage tries to build scheme "RxBluetoothKit iOS"
```
/RxBluetoothKit/Source/Descriptor.swift:27:33: error: Superfluous Disable Command Violation: SwiftLint rule 'line_length' did not trigger a violation in the disabled region. Please remove the disable command. (superfluous_disable_command)
Done linting! Found 3 violations, 1 serious in 29 files.
```
The offending line is 
`// swiftlint:disable line_length`
removing it seems to fix the problem. Also the "RxBluetoothKit macOS" scheme seems to build fine with or without this line.

**Comment by Kacper20** [comment]
That's weird. Which version of swiftlint do you have installed on your system?

**Comment by zhentan** [comment]
`swiftlint version` returned
`0.22.0`

**Comment by qbraet** [comment]
same error for me, same swiftlint version

**Comment by Kacper20** [comment]
It's fixed on newest release. Sorry for the issue.
