### ISSUE TITLE
Support Swift4

### ISSUE THREAD

**Issue by Jenus** [Polidea/RxBluetoothKit#143]
When Xcode 9 with swift 4 has released,  it was urgent to support using RxSwift 4.0.0;
After my experiment, RxSwift new api style has no changed for RxBluetoothKit. Hope so soon to start migration. Thanks very much!

**Comment by Cierpliwy** [comment]
There is initial release which supports both RxSwift4 and Swift 4:
https://github.com/Polidea/RxBluetoothKit/releases/tag/4.0.0-alpha.0

**Comment by RamblinWreck77** [comment]
@Cierpliwy  just a heads, up, it appears the alpha release's podspec hasn't been updated, still depends on RxSwift 3.x

**Comment by Kacper20** [comment]
We have released new version: https://github.com/Polidea/RxBluetoothKit/releases/tag/4.0.0-alpha.1
