### ISSUE TITLE
4.0.0 alpha 0 release has incorrect podspec

### ISSUE THREAD

**Issue by RamblinWreck77** [Polidea/RxBluetoothKit#145]
`s.dependency 'RxSwift', '~> 3.2'`

should be

`s.dependency 'RxSwift', '~> 4.0'`

**Comment by Jenus** [comment]
Yes. Althrough Cartfile can support Swift 4 and RxSwift4. Expected pod will be supported soon, thanks.

**Comment by Kacper20** [comment]
I've just released this as `alpha.1` version

**Comment by Jenus** [comment]
RxSwift version is changed quickly, so it would better to use its coming rc (4.0.0 rc.0) or stability version?

**Comment by Jenus** [comment]
When its stability version was released, I will to go here to notify it. haha

**Comment by Jenus** [comment]
RxSwift had released 4.0.0 already. So appreciated to support this version!
