### ISSUE TITLE
Can not run RxBluetoothKit (Swift 4.0) on iPhone 5c (10.3 iOS)

### ISSUE THREAD

**Issue by rgarciaotc** [Polidea/RxBluetoothKit#149]
I am trying to run the example with my own device and can not do it because at the time that I choose my own device i can not acceded to any method of the library, if I jump, I just can see autogenerated code by xcode. But if I select a simulator device i can Jump to the definition and see all the implemented methods.
![captura de pantalla 2017-10-03 a las 10 02 18](https://user-images.githubusercontent.com/32128637/31119129-3d793a16-a830-11e7-9478-66331ae65dbf.png)
![captura de pantalla 2017-10-03 a las 10 03 08](https://user-images.githubusercontent.com/32128637/31119132-3dfc7ebc-a830-11e7-9d3d-a54f55a9b6f7.png)
![captura de pantalla 2017-10-03 a las 10 04 31](https://user-images.githubusercontent.com/32128637/31119131-3dd74a52-a830-11e7-85b4-745e6a1ac76b.png)

**Comment by Kacper20** [comment]
We haven't updated the example for Swift 4.0 yet. I will do this today and make sure that all works as expected.

**Comment by rgarciaotc** [comment]
Really thanks I guess can find it at swift 4.0 branch.

**Comment by Kacper20** [comment]
Yes, will be available in a couple of hours. Thanks for the patience!

**Comment by rgarciaotc** [comment]
I know you are making changes, but I can not understand why when I try to build I can not find any method from RxBluetoothKit, why xcode autogenerated some code instead of let me see the implemented methods.

**Comment by Kacper20** [comment]
I'm not sure why it's like that. Right now working example is available on the `swift4` branch. Please run `pod repo update` and `pod install` to make it running :)
