### ISSUE TITLE
After connecting and discovering a chracteristic setnotificationandmonitorupdates fires a change error

### ISSUE THREAD

**Issue by Neogene** [Polidea/RxBluetoothKit#161]
Hi, after I detect all the bt devices I want to liste to a specific message, docs say:

>  Servcie Main UUID:0xFFE0  Sub UUID：0xFFE1 prop= CHAR_PROP_READ | CHAR_PROP_NOTIFY     The command format is as follows Byte0 0x00 Each click a button, to send one time data; click on camera interface to take photos;  Positioning on other interface; Dual click trigger alarm or record  

Using the following code sends after the setNotificationAndMonitorUpdates the error: "Characteristic notify change error has occured: The attribute could not be found."

I receive properly the characteristic.monitorValueUpdate callback

```
peripheral.connect()
            .flatMap { $0.discoverServices([CBUUID.init(string: "FFE0")]) }
            .flatMap { Observable.from($0) }
            .flatMap { $0.discoverCharacteristics([CBUUID.init(string: "FFE1")])}
            .flatMap { Observable.from($0) }
            .flatMap { $0.readValue() }
            .subscribe(onNext: { characteristic in
                print("Discovered characteristic: \(characteristic.uuid.uuidString)")
                characteristic.monitorValueUpdate()
                    .subscribe(onNext: {characteristic in
                        print("update detected \(characteristic)");
                    })
                characteristic.setNotificationAndMonitorUpdates()
                    .subscribe(onNext :{ characteristic in
                        print("subs: \(characteristic)")
                    })
            } )

```
Something I don't get too reading the docs and the test project is how to set to reconnect automatically the device, I use these commands to connect and scan (mainly copied from the test project). Following code also fails when starting app with BT off, and due to 4s timeout it stops to monitor, there is way to listen when bt is enabled again?

  ```
 scanningDisposable = manager.rx_state
            .filter { $0 == .poweredOn } //required to avoid "Bluetooth is in unknown state error"
            .timeout(4.0, scheduler: scheduler)
            .take(1)
            .flatMap { _ in
                self.manager.scanForPeripherals(withServices: [CBUUID.init(string: "FFE0")], options: nil)
            }
            .subscribeOn(MainScheduler.instance)
            .subscribe(onNext: {
                print ("onnext...");
                self.addNewScannedPeripheral($0)
            }, onError: { error in
                print ("error...\(error)");
                DispatchQueue.main.async {
                    self.delegate?.didFailScanning()
                }
            })
```

Thank you, sorry but it's first time I use rx

**Comment by Kacper20** [comment]
Hi there,

After reading your questions I assume that you have two questions.
## BT State issue
It really depends on your logic. You could just wrap all your logic into a function. Inside onError you could check for a timeout error. Then just call this function that subscribes to state again. It all depends on your logic — do you want to show the error to the user? If not you could omit the timeout operator. If you want to have some specific behaviour — please let me know and I'll give you a hints.

## Reconnection
To reconnect after you establish the connection you should begin subscription to `monitorPeripheralDisconnection`. After event that is informing about the disconnection is emitted you should try connect again to the peripheral.

**Comment by Kacper20** [comment]
Hi @Neogene,
Any updates? Does it answers your concerns?

**Comment by Kacper20** [comment]
Closing as of now. Please feel free to reopen the issue if you have any additional questions! :)
