### ISSUE TITLE
[5.0] Prevention from stealing delegates between Peripheral instances, way to (re-)attach delegate.

### ISSUE THREAD

**Issue by Kacper20** [Polidea/RxBluetoothKit#163]
# Stealing delegates inside of our library
Let’s imagine the stream of `Peripheral` instances which looks as follows in the code: `Observable<Peripheral`. The source of values is Bluetooth scan. Underneath whenever we’re receiving new `CBPeripheral` on delegate callback there is new `Peripheral` instance created. Inside creation of `Peripheral` we’re creating new delegate proxy object. Let’s make an assumption tthat stream emits duplicate peripherals (like it currently when [this particular](https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerscanoptionallowduplicateskey?language=swift) option is set to `true`).
Then, every time that duplicate is emitted it has different memory address and all of the predecessors are unusable right now (because the delegate on this particular `CBPeripheral` that is bound to our objects is overwritten by the newest instance). This behavior may be confusing to the users of the library. To mitigate this behavior we propose to introduce caching layer inside the `BluetoothManager`. If `Peripheral` is currently in cache we would like to get it from there and not create another instance. It’ll have proper delegates set. There are many possible implementations — it’s up to the contributor taking this issue to propose something more detailed. One edge-case to have in mind is to always check whether `CBPeripheral` discovered has our own proxy object set. If not we should probably reattach delegate to it (as it would be done when creating `Peripheral` object). Since now it’ll be cached we should be making this additional check.

# Stealing delegates outside of our library
User of our library has access to the underlying `CBPeripheral` and `CBCentralManager` objects. This objects could be used to access them in a non-reactive way or pass to the external library like [Nordic-DFU](https://github.com/NordicSemiconductor/IOS-DFU-Library). While doing this the certain thing is that delegate will be overwritten. Currently our library doesn’t give any way to reattach delegate to our objects like `BluetoothManager` and `Peripheral` which are managing `CBCentralManager` and `CBPeripheral` objects.

This proposal suggests adding function `attach()` to these two classes. Implementation of the function would reassign the delegate of managed objects to our reactive delegate proxies.

# How it affects current users
It’ll make using our library along with other ones (like Nordic firmware update) more pleasant. API changes are clearly additive.

# Tasks
- [x] Stealing delegates inside our library
- [ ] Stealing delegate outside of our library

**Comment by paweljaneczek** [comment]
Done in #202
