### ISSUE TITLE
Support for CBPeripheralManager

### ISSUE THREAD

**Issue by Kacper20** [Polidea/RxBluetoothKit#166]
Our library currently only supports `CoreBluetooth` central mode. 
New object would be named `PeripheralManager` (with consistent naming to `CentralManager`)

# Design
Since `CBCentralManager` and `CBPeripheralManager` both inherit from `CBManager` which consist `state` property it would be appropriate to map the same relationship in our hierarchy in order to avoid code duplication. It could be named `BaseManager` and should take `CBManager` instance in initializer. This class would expose functions that operate on state, that currently belong to the `BluetoothManager`, like continuous access to `BluetoothState`.
Then, both new `CentralManager` and `PeripheralManager` would inherit from `BaseManager`.

Design of `PeripheralManager` should be analogous to the current `CentralManager` (After changes from #162 . One that implements it should perform pairing of methods from `CBPeripheralManager` and the delegates callbacks. Then, every method should be wrapped in an reactive way. Delegate proxy for the `CBPeripheralManagerDelegate` should also be created.

In [What’s New in CoreBluetooth, 712, WWDC 2017](https://developer.apple.com/videos/play/wwdc2017/712/) session Apple has announced couple of new APIs as a part of iOS 11 & macOS 13. We would like to support it in our reactive wrappers.

## L2CAPChannels
There were 2 main API changes introduced: L2CAPChannels capabilities in `Central` modes of the CoreBluetooth and enhancements in write without response. L2CAPChannels change should be also a part of #166 task.

`CBPeripheralManager` instance contains two methods for publishing and unpublishing channels:
- `publishL2CAPChannel(withEncryption: Bool)`
- `unpublishL2CAPChannel(CBL2CAPPSM)`
These two have delegate methods that inform about the success of each operation. Exposed interface should be as follows:
- `func publishL2CAPChannel(withEncryption: Bool) -> Observable<CBL2CAPPSM>`
- `func unpublishL2CAPChannel(CBL2CAPPSM) -> Observable<CBL2CAPPSM>`
Implementation is pretty standard —> connection to the delegate methods and performing function call on `CBPeripheralManager` instance. Proper errors should be introduced as a part of `BluetoothError` structure.

We should also allow user to monitor openings of `L2CAPChannel`. To do this we should expose function like `func monitorL2CAPChannelOpenings -> Observable<CBL2CAPChannel`. It would connect to [this](https://developer.apple.com/documentation/corebluetooth/cbperipheralmanagerdelegate/2880154-peripheralmanager) delegate method. We should probably provide function like `publishAndMonitorOpeningsOfL2CAPChannel`. Basically the design should be analogous to the setting notification as enabled and monitoring notifications on `CBCharacteristic`.

### L2CAPChannel
It’s a wrapper around `CBL2CAPChannel` CoreBluetooth object. It should only be created if we would decide to wrap `InputStream` and `OutputStream` properties of `CBL2CAPChannel` into reactive wrappers. If it’ll not be the case (and it *probably* shouldn’t be) — all of the interface methods should simply return directly `CBL2CAPChannel` objects.

# Affection to current users
Additive changes

**Comment by paweljaneczek** [comment]
@danielbotka hey, we are on the final steps before releasing RC version with `PeripheralManager` support. 
Problem here is that currently we are not developing any project that will use that feature. Would you like to test it before releasing stable version?

**Comment by danielbotka** [comment]
@paweljaneczek hey, yes, I'd be happy to play around a little, probably next week. Is it on a specific branch?

**Comment by paweljaneczek** [comment]
@danielbotka great to hear! In next week we will have probably RC library version so we will give a sign to you in this thread

**Comment by jodm** [comment]
@paweljaneczek We also have a project that we could integrate this into. Should I try and integrate from the `feature/peripheral_manager` branch?

**Comment by paweljaneczek** [comment]
@jodm great! For now the newest changes are on `feature/peripheral_manager_tests`

**Comment by paweljaneczek** [comment]
@jodm @danielbotka We've just release version 5.1.0 with support for `PeripheralManager`. If you will find any bugs/problems for it just fill new issue on github. Closing this one.
