### ISSUE TITLE
[5.0] `monitorDisconnection` set of methods should emit `.next` along with `.error` in Observable stream

### ISSUE THREAD

**Issue by Kacper20** [Polidea/RxBluetoothKit#167]
Currently method that allows for monitoring disconnection of Peripheral is emitting `.next` on Observable stream, when proper delegate method fires (`centralManager(_:didDisconnectPeripheral:error)`). Semantically whenever other `BluetoothError` instances like are emitted (like `CBCentralManagerState` becomes .unauthorized) — the peripheral is also becoming disconnected. We would like in this case emit both `.next` and `.error` on the stream.

# Design
Inside the implementation for the monitor disconnection we should check for proper errors and map them into sequence of element and error. 

# How it affect current users
None affection

**Comment by paweljaneczek** [comment]
Done in #206
