### ISSUE TITLE
[5.0] New testing infrastructure

### ISSUE THREAD

**Issue by Kacper20** [Polidea/RxBluetoothKit#168]
As a part of #162 all of the tests and the current testing infrastructure will be removed. Rationale behind this decision is written as a part of the #162. 
We would like to perform testing based on the code generation. Basically every implementation class we currently have should have code generated that will use stubs instead of concrete `CB` objects. 
This way we will not have code that we want to duplicate and our architecture and code we write will be independent of testing infrastructure.
# Design
We should use something like `Sourcery` to perform codegen of the new classes. All of the tests for the library should be rewritten. 
Earlier we’ve used `Quick` and `Nimble` for testing. It was partially unfortunate choice — we have lot’s of tests that should be generic. For example: We should check bluetooth error propagation for literally every call that involves any Bluetooth operation. `Quick` at the time of writing tests in 2016 didn’t have enough support for generic testing methods. 

As part of this task there should re-evaluation of `Quick` capabilities. If it haven’t changed since 2016 we advise to use standard `XCTests` to avoid duplication of code. 

# Does it affects current users
No.

**Comment by paweljaneczek** [comment]
Done in #200
