### ISSUE TITLE
[5.0] Simplifying scanning logic

### ISSUE THREAD

**Issue by Kacper20** [Polidea/RxBluetoothKit#179]
Currently the scanning logic is quite complicated. Our method assumes that user could invoke multiple scans at the same moment. It takes care of storing scans, returning connectable observables and scans queueing. When thinking more about this we believe that it doesn’t make sense to keep it that way. We should only allow to have one scan at the moment and issue an error if user want to use our function in a different way.

This will allow us to remove our custom queue scheduling and operators. Should also finally resolve #84. 

# Impact on current users
This changes shouldn’t reflect the API. We would need to change documentation and include this change in a `CHANGELOG.md`

**Comment by paweljaneczek** [comment]
Done in #206
