### ISSUE TITLE
`discoverCharacteristics/Services` never completes if it can't find all

### ISSUE THREAD

**Issue by sirlantis** [Polidea/RxBluetoothKit#182]
The documentation states this:

> Next on returned `Observable` is emitted only when all of the requested characteristics are discovered. [...] Immediately after that `.Complete` is emitted.

However I observed that if some characteristic is not found, I never see a `.complete`.

This is the code in question:

```
let observable = peripheral
            .rx_didDiscoverCharacteristicsForService
            .filter { $0.0 == service.service }
            .flatMap { (cbService, error) -> Observable<[Characteristic]> in
                guard let rxCharacteristics = cbService.characteristics, error == nil else {
                    throw BluetoothError.characteristicsDiscoveryFailed(service, error)
                }
                let characteristics = rxCharacteristics.map { Characteristic(characteristic: $0, service: service) }
                if let filteredCharacteristics = filterUUIDItems(uuids: characteristicUUIDs, items: characteristics) {
                    return .just(filteredCharacteristics)
                }
                return .empty()
            }
            .take(1)
```

Should the `.take(1)` be moved in front of `flatMap` or would that change create new bugs if multiple scans are happening in parallel?

If you want I can put up a PR, but wanted to make sure first that I didn't misunderstand the intention of this API.

**Comment by paweljaneczek** [comment]
Thanks for informing about it!

We have already fixed that issue in version 5.0, which will be released very soon.
