### ISSUE TITLE
What is serviceIds

### ISSUE THREAD

**Issue by rohitnewscorp** [Polidea/RxBluetoothKit#185]
I just started this library. It is well-explained library except for one thing i.e  What is `serviceIds `? and how can I create it? Kindly help as I need to integrate this library as soon as possible.

Thanks & regards

**Comment by bartoszstelmaszuk** [comment]
What exactly `serviceIds` you are mentioning about? 

Is it `ServiceIdentifier` protocol defined in `DeviceIdentifiers` file? If it is than this convenience protocol allows you to represent your services handles as enum cases and makes it easier to get discovered services.
You can read service identifiers from manufacturer's documentation or by scanning and exploring your bluetooth device.

**Comment by paweljaneczek** [comment]
Closing due to no answer. @rohitnewscorp If you have any questions please open new ticket
