### ISSUE TITLE
Not able to find peripheral name

### ISSUE THREAD

**Issue by rohitjb** [Polidea/RxBluetoothKit#190]
Hi 

I am working on an app where I need to show the name of devices in a list which are in the bluetooth range so I am using this library which is really cool but the issue is I am not able to find the name of peripheral. Kindly help me with this.

Thanks & regards

**Comment by bartoszstelmaszuk** [comment]
Can you give some more information about how you try to find the name of peripheral on app side? Is it problem to discover a device or you discover device but couldn't read the name from data?

Most importantly tell more about device. Does it transmit proper `advertisementData` so it could be discovered? iOS tends to cache `localName` so maybe app at the beginning receives different name than you suspect and returns it later from cache?

**Comment by paweljaneczek** [comment]
@rohitjb do you still have a problem or is it already resolved?

**Comment by paweljaneczek** [comment]
Closing due to no answer. @rohitjb If you have any questions please open new ticket
