### ISSUE TITLE
Getting CLBeacon to get major and minor version

### ISSUE THREAD

**Issue by nneuberger1** [Polidea/RxBluetoothKit#191]
How do I get the major and minor version from this toolkit.  I'm a bit new to BTLE technology and found this link on CLBeacon.  However, I'd like to use this library for accessing it via Rx.

https://www.raywenderlich.com/152330/ibeacon-tutorial-ios-swift

Any thoughts?

**Comment by Cierpliwy** [comment]
This library is a wrapper around `CBCentralManager`, `CBPeripheral`, `CBService` etc. which are part of Core Bluetooth module. Core Location module (which defines CLBeacon) is not covered by RxBluetoothKit.
