### ISSUE TITLE
Triggering re-scan turns off scanning

### ISSUE THREAD

**Issue by mwoollard** [Polidea/RxBluetoothKit#192]
Take the following intending to re-scan for peripherals every 5 minutes. Only the first scan request works. Debugging shows that the existing scan observable is picked for re-use and then that observable's dispose closure fires afterwards removing the observable wrapper from the queue and issuing a stop scan call to CB manager leaving an observable that will never emit any events.

```
        manager.rx_state
            .filter { $0 == .poweredOn }
            .take(1)
            .flatMap { _ in Observable<Int>.timer(0, period: 300, scheduler: MainScheduler.instance) }
            .flatMapLatest { _ in manager.scanForPeripherals(withServices: nil) }
            .subscribe()
```

**Comment by Cierpliwy** [comment]
Did you test version 4.0.1?

**Comment by paweljaneczek** [comment]
Closing due to no answer. @mwoollard If you have any questions please open new ticket
