### ISSUE TITLE
Unable to infer complex closure return type; add explicit type to disambiguate

### ISSUE THREAD

**Issue by vitorventurin** [Polidea/RxBluetoothKit#195]
When I try:

manager.scanForPeripherals(withServices: [servicesId])
      .flatMap { scannedPeripheral in //error line
        let advertisement = scannedPeripheral.advertisement
    }

I receive an error message: Unable to infer complex closure return type; add explicit type to disambiguate

**Comment by DevAndArtist** [comment]
This is Swift not able to infer the type for you and due the complexity of `RxSwift`. Do as the compiler error says and provide explicit type like `(scannedPeripheral: Peripheral) -> Observable<Peripheral>`.

But to be honest, this is simply a wrong example from the README. `.flatMap` simply makes not sense for that example. Exchange it with `.subscribe(onNext: { scannedPeripheral in })`.

**Comment by paweljaneczek** [comment]
Changed readme in #203. Closing.
