### ISSUE TITLE
Auto Pair 

### ISSUE THREAD

**Issue by inovatek** [Polidea/RxBluetoothKit#204]
Hello

Can this library autopair programmatically ?

Thank You Very Much !!

**Comment by paweljaneczek** [comment]
`RxBluetoothKit` is just an reactive wrapper around CoreBluetooth classes, so there is no autopair. If you want auto connect to device you could:
- connect to device and save it's uuid
- on every disconnect or app restart use this uuid to connect to that save device
Is this an answer for your question?

**Comment by yakovzvi** [comment]
Is it possible to communicate to the ble device even without pairing ? Similar to a advertising tag ?

Thank You Very Much !!
Yanky

**Comment by paweljaneczek** [comment]
Yes, check this answer https://stackoverflow.com/a/25255450

**Comment by paweljaneczek** [comment]
For now closing. @yakovzvi If you have any other doubts, please reopen issue
