### ISSUE TITLE
Update API documentation with a list of errors

### ISSUE THREAD

**Issue by DevAndArtist** [Polidea/RxBluetoothKit#225]
Please update documentation for all properties and functions that return an `Observable` or a different RxSwift type with a list of all possible errors that particular sequence can throw. It is literally very painful to recursively dig through the entire implementation to find all possible errors that can happen on each sequence.

**Comment by paweljaneczek** [comment]
@DevAndArtist I've added it in  #250. Please take a look if you will have time

**Comment by paweljaneczek** [comment]
Done in #250
