### ISSUE TITLE
Add `Podfile` to the repo

### ISSUE THREAD

**Issue by DevAndArtist** [Polidea/RxBluetoothKit#231]
Please add `Podfile` to the repository so contributors don't have to regenerate it from scratch.

**Comment by minixT** [comment]
We use Carthage instead CocoaPods. If you want to contribute, you can run `carthage update` in root folder. This will install all necessary dependencies.

**Comment by DevAndArtist** [comment]
@minixT Woops sorry, I somehow didn't noticed that at all. Carthage is fine too.
