### ISSUE TITLE
Example is not up-to date with ver 5.0.0

### ISSUE THREAD

**Issue by zdravkin** [Polidea/RxBluetoothKit#240]
Since there are a lot of changes between ver. 4.1 and 5.0.0, I think it will be useful to have the example app up to date in order to test the changes.

**Comment by minixT** [comment]
We are working on a new example app.  It is developed on the [example_app_5.0](https://github.com/Polidea/RxBluetoothKit/tree/feature/example_app_5.0) branch

**Comment by paweljaneczek** [comment]
Done in #220
