### ISSUE TITLE
[5.0] Error case `peripheralIsConnectingOrAlreadyConnected` is misleading

### ISSUE THREAD

**Issue by DevAndArtist** [Polidea/RxBluetoothKit#245]
I reviewed the changes made in https://github.com/Polidea/RxBluetoothKit/pull/242 and from the standpoint of the new implementation the error case becomes misleading because it will only fail if one observable was previously created.

I'd propose to rename the case to something like `isAlreadyObservingConnection`.

**Comment by paweljaneczek** [comment]
@DevAndArtist Hey, good point. Could you look at https://github.com/Polidea/RxBluetoothKit/pull/249 and check if it looks ok?

**Comment by paweljaneczek** [comment]
Fixed in #249
