### ISSUE TITLE
observeConnection 

### ISSUE THREAD

**Issue by LiuSky** [Polidea/RxBluetoothKit#248]
I used to use 4 rx_isConnected for a good time. But with a 5 observeConnection, this will automatically call the disconnected method observeDisconnect after my active connection. I don't know what it was. I'm confused. @minixT

**Comment by LiuSky** [comment]
I will automatically disconnect when I connect with an event, but the 4 version is normal. Do not take the initiative to disconnect. I don't know what logic has caused by 5. @minixT

**Comment by LiuSky** [comment]
When the connection is successful, a callback method is returned within a few seconds. 4.0 does not.

**Comment by LiuSky** [comment]
Thank you for your reply. I want to know why it is designed. gratitude @paweljaneczek

**Comment by paweljaneczek** [comment]
There were several reasons of that:
- simplified use of api - now there is no need of calling separately `disconnect`, it is done automatically when disposing
- it is more reactive style of coding
- have the same api as our android library, which will be easier for us to maintain it and reuse it in our react-native and flutter libraries

**Comment by LiuSky** [comment]
Is there a way to take the initiative? @paweljaneczek

**Comment by paweljaneczek** [comment]
Not sure what you mean. Would you like to contribute to library?

**Comment by LiuSky** [comment]
5.0 version, I just started reading in the afternoon, but I don't know the logic of 5.0 at the moment.

**Comment by LiuSky** [comment]
Is there any way I can't take the initiative to disconnect when I call establishConnection? @paweljaneczek  Thank you

**Comment by paweljaneczek** [comment]
The only way to disconnect (using our library) is to dispose `observeConnection` subscription.

**Comment by LiuSky** [comment]
I'm sorry, maybe my expression is not very clear. My problem is that I actively invoke the establishConnection method, and after the link is successful, he will take the initiative to disconnect the connection, rather than I call it manually.
<img width="963" alt="2018-04-16 4 07 05" src="https://user-images.githubusercontent.com/3087745/38797210-5eecd76c-4190-11e8-97dd-27839689eb0a.png">
<img width="1130" alt="2018-04-16 4 08 27" src="https://user-images.githubusercontent.com/3087745/38797228-711e2b2a-4190-11e8-9ceb-a7e1178ae89a.png">

**Comment by paweljaneczek** [comment]
could you also share code when you are subscribing for that observable?

**Comment by LiuSky** [comment]
Sorry, I don't quite understand your meaning, or wait for the sample project. Thank you @paweljaneczek
