### ISSUE TITLE
Support for state restoration and preservation

### ISSUE THREAD

**Issue by mane87** [Polidea/RxBluetoothKit#25]
Hi,
is state restoration and preservation supported? I could not find anything in the docs.
As far as i can tell from the sourcecode, it is not implemented

Is there any plan on implementing it?

Thanks for the awesome work so far 💯 👍

**Comment by literator** [comment]
Hi,

Thanks for the feedback! We plan to dig in more into state restoration &
preservation topics and support for them.

Do you have particular needs or nice-to-haves regarding this API?

Cheers,
W dniu wt., 17.05.2016 o 14:12 Manuel Zoderer <notifications@github.com>
napisał(a):

> Hi,
> is state restoration and preservation supported? I could not find anything
> in the docs.
> As far as i can tell from the sourcecode, it is not implemented
>
> Is there any plan on implementing it?
>
> Thanks for the awesome work so far 💯 👍
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Polidea/RxBluetoothKit/issues/25>
>
-- 
Maciej Oczko

**Comment by mane87** [comment]
Hi,
thanks for the fast answer!

So, i am currently building a prototype app for our startup:
http://timeular.com
(Please have look and you should get the idea pretty fast ;) )

Obviously, my app should be notified about changes for the up-facing-side (we use an accelerometer) of my accessory. Thats why i want to use state restoration and preservation.

If you could guide me i would also love to help you to implement it.

Cheers, Manuel

**Comment by mhle** [comment]
I would love to see this feature as well! is there a workaround we can use until it's done? I.e. do we have access to the underlying corebluetooth functionality? Our app interacts with multiple BLE devices and needs to know when they're switched on and off so continuously needs to scan.

Cheers, 

Michael

**Comment by Kacper20** [comment]
Hi,
Are you talking about `willRestoreState` from `CBCentralManager`?
It's not visible yet, but we can do this fairly quickly. I have never worked with state restoration. Do we need to do anything more? 
From our side - I'll  do research over the weekend, and will talk to you back after that. 

Thanks for using library and have a great weekend!

**Comment by Kacper20** [comment]
Hi,
I've looked at it and it looks like it should be pretty easy to implement. Will do it probably in monday / tuesday. Once we'll test it it'll be released :)

Thanks for feedback

**Comment by mane87** [comment]
Hi,
thanks for the awesome work!!
Once is ready i am going to test it and provide feedback.

Thanks again for the awesome work you are doing 💯 👍

**Comment by mhle** [comment]
Thanks for quick reaction, looking forward to testing this new feature out! 👍

**Comment by Kacper20** [comment]
Hi,
Today we've pushed 1.2 version, which contains requested features.
Please check it out and let us know about your impressions. 

Regards

**Comment by mhle** [comment]
Super, thanks for acting so fast!

Cheers, 

Michael
