### ISSUE TITLE
write .withoutResponse crash on iOS < 11

### ISSUE THREAD

**Issue by JRock007** [Polidea/RxBluetoothKit#253]
When using a device with iOS 10 or less, calling write without response produces a crash:

> Peripheral.swift line 83
`-[CBPeripheral canSendWriteWithoutResponse]: unrecognized selector sent to instance`

To fix it, I replaced
``` swift
public var canSendWriteWithoutResponse: Bool {
    return peripheral.canSendWriteWithoutResponse
}
```
with
``` swift
public var canSendWriteWithoutResponse: Bool {
    if peripheral.responds(to: #selector(getter: CBPeripheral.canSendWriteWithoutResponse)) {
        return peripheral.canSendWriteWithoutResponse
    }
    return true
}
```

There probably is a better way of handling it, but at least this prevents crashes and allows writing as long as the device has space

**Comment by paweljaneczek** [comment]
Fixed in #254.
