### ISSUE TITLE
Issue with running the Example

### ISSUE THREAD

**Issue by c0ng7u** [Polidea/RxBluetoothKit#26]
First of all, thanks so much for building an awesome bluetooth library, at least for a newbie like me. I was trying to run the Example project and ran into some errors. Could you please point me to the right direction? 

Thank you very much.

(screenshot attached)

![screen shot 2016-05-23 at 12 03 43 am](https://cloud.githubusercontent.com/assets/19365913/15460387/7d629798-207e-11e6-84cf-69079d8955be.png)

**Comment by Kacper20** [comment]
Hi,
Which version of a lib your're using?

**Comment by c0ng7u** [comment]
Thanks for your quick response. It's RxBluetoothKit (0.3.2)

**Comment by Kacper20** [comment]
Hi,
Please update to the newest 1.1.1 version and let me know if everything works fine.

**Comment by c0ng7u** [comment]
version 1.1.1 did the trick. In the podfile, if I used just 
pod 'RxBluetoothKit' 
it would keep downloading the 0.3.2 version. I had to use
pod 'RxBluetoothKit', :git => 'https://github.com/Polidea/
in order to get the 1.1.1

Thank you for you help

**Comment by Kacper20** [comment]
Thats weird. It should download it automatically. But I'm glad that it works now. If you have any questions feel free to ask - we're happy to help. 
Regards
