### ISSUE TITLE
Update 5.1.1 `.framework`

### ISSUE THREAD

**Issue by DevAndArtist** [Polidea/RxBluetoothKit#268]
Here is what Carthage reports:

> *** Skipped installing RxBluetoothKit.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2) and the local version is 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)."

You may want to update the binary.

**Comment by paweljaneczek** [comment]
@DevAndArtist thanks for issue! I've fixed it with releasing version 5.1.2.
