### ISSUE TITLE
RxBluetoothKit 5.1.2 - Deployment target is iOS 10

### ISSUE THREAD

**Issue by Drusy** [Polidea/RxBluetoothKit#275]
**Describe the bug**
Deployment target is iOS 10 in RxBluetoothKit v5.1.2

**Expected behavior**
Documentation says iOS 8.0+

**Environment:**
 - Library version 5.1.2
 - Swift version 4.1

**Comment by Drusy** [comment]
In the framework (compiled with Carthage), the generated Info.plist file now shows:
```
<key>MinimumOSVersion</key>
<string>10.0</string>
```

When is was previously
```
<key>MinimumOSVersion</key>
<string>8.0</string>
```

**Comment by paweljaneczek** [comment]
Yeah, it looks like I've changed it by mistake when I've been adding `PeripheralManager`. Will release new version with minimum 8.0 today.

Thanks for reporting!
