### ISSUE TITLE
can an app mimic a peripheral?

### ISSUE THREAD

**Issue by dam13n** [Polidea/RxBluetoothKit#277]
kind of a general question: when your app hears a bluetooth event (like a button press), can you re-emit it to the OS? i want to change the default behavior of bluetooth devices, like play/pause buttons for example, but i'm not sure if you can intercept a signal and then pass it or a different one back.

**Comment by paweljaneczek** [comment]
Thanks for using our library!
Unfortunately this question is not related to our library and I have no knowledge about this. I think better would be to ask that question on stackoverflow.

**Comment by paweljaneczek** [comment]
Closing for now, if you feel that it should be reopen, please give a sign.
