### ISSUE TITLE
Ambiguous use of from

### ISSUE THREAD

**Issue by AndrewSB** [Polidea/RxBluetoothKit#28]
The library is great! Having one issue when I drag the `RxBluetooth` source code directly into my project. I get an error on every use of `Observable.from`, saying that use of `from` is ambiguous.

Any idea why this may be happening or how I can debug this?

**Comment by AndrewSB** [comment]
Works great when I use Carthage

**Comment by Kacper20** [comment]
Hi there,
We have never tried to integrate it directly, so it may not work as it should at the moment. We'll check it tomorrow and let you know about the solution right away .

Thank you very much for feedback,

**Comment by Kacper20** [comment]
Hi,

Could you include sample project here? It would be very helpful. :-)

**Comment by literator** [comment]
@AndrewSB @Kacper20 any update here?
