### ISSUE TITLE
Cartifile not pointing to RxSwift 4.3.1

### ISSUE THREAD

**Issue by raviranderia** [Polidea/RxBluetoothKit#291]
Looks like the cart file hasn't been updated to point RxSwift to version 4.3.1 for Swift 4.2 support.

**Comment by bartoszstelmaszuk** [comment]
Thanks for your message!

As far as I can tell by looking at RxSwift commits there have been some crucial fixes to make it work on macOS with Swift 4.2. We will update Cartfile to RxSwift 4.3.1

**Comment by raviranderia** [comment]
works now! thanks for the quick response.
