### ISSUE TITLE
Read or Write to a Characteristic leads to disconnect.

### ISSUE THREAD

**Issue by PaulEhrhardt** [Polidea/RxBluetoothKit#299]
**Describe the bug**
Using RxBluetoothkit, `read` or `write` to a Characteristic leads to immediate disconnect.
Read/Write action is possible on the same device when directly using Apple CoreBluetooth.

**To Reproduce**

1. Using sample code:
I use the example sequence on to of the [Readme](https://github.com/Polidea/RxBluetoothKit/blob/master/README.md)
```
manager.scanForPeripherals(withServices: [serviceId])
    .take(1)
    .flatMap { $0.peripheral.establishConnection() }
    .flatMap { $0.discoverServices([serviceId]) }
    .flatMap { Observable.from($0) }
    .flatMap { $0.discoverCharacteristics([characteristicId]) }
    .flatMap { Observable.from($0) }
    .flatMap { $0.readValue() }
    .subscribe(onNext: { print("Value: \($0.value)") })
```

2. Using Example App:
I encounter the same disconnect behaviour on read/write value.
![48630912-acae6080-e9bd-11e8-9588-64c99a65a8fb](https://user-images.githubusercontent.com/5812406/48695142-a2b77800-ebde-11e8-8082-2a0da6f1cb2a.png)

**Expected behavior**
`readValue(...)` and `writeValue(...)` on Characteristic should be possible.

**Environment:**
 - Device: [iPhone6Plus]
 - OS: [iOS12, macOS 10.14.1]
 - Library version [5.1.4]
 - Swift: [4.2]

**Comment by PaulEhrhardt** [comment]
Further investigation tuned out that the problem was unfortunately device related. 
I will close this issue as no action is needed from your side.

**Comment by krutitrivedi** [comment]
from where you get serviceID because i get error
