### ISSUE TITLE
ExampleApp run a lot with no result

### ISSUE THREAD

**Issue by FedericoSub** [Polidea/RxBluetoothKit#308]
**Describe the bug**
Hi I'm sorry for my question, I don't think its a bug but my mistake.
I'm running on my mac with swift 4.2 the ExampleApp , click on Start Scan but not discover my BLE device in Power on.
Must I config something ?

Thank 

Federico

**To Reproduce**

**Expected behavior**

**Environment:**
 - Device: [e.g. iPhone X, Macbook Pro 2018]
 - OS: [ macOS 10.14.2]
 - Library version [e.g. 5.1.2]
 - Swift version [e.g. 4.2
<img width="1280" alt="schermata 2019-01-27 alle 21 16 57" src="https://user-images.githubusercontent.com/35109594/51806329-09a97b00-2279-11e9-909a-1f6745271c35.png">
]

**Comment by dariuszseweryn** [comment]
BLE functionality does not work on simulator.
