### ISSUE TITLE
discoverServices doesn't emit any result

### ISSUE THREAD

**Issue by vladiulianbogdan** [Polidea/RxBluetoothKit#309]
**Describe the bug**

The problem is that in our code we have multiple places where we discover services. The peripheral that the app connects to is also sometimes emitting a service change indication (I don't know if it is relevant).

What I've seen is that sometimes the `discoverServices` does not emit anything. I've deep dived into the code and the problem is around `remainingServicesDiscoveryRequest`. Sometimes the value in `remainingServicesDiscoveryRequest` remains unbalanced (it has value 1).

I will keep you posted if I discover what is causing the variable to be unbalanced.

**Expected behavior**

`discoverServices` should always emit the discovered services.

**Environment:**

 - Device: iPod, MacBook Pro  2018
 - OS: 10.13.6
 - Library version 5.1.3
 - Swift version 4.2

**Comment by c0diq** [comment]
Probably related to https://github.com/Polidea/RxBluetoothKit/issues/287

**Comment by minixT** [comment]
@vladiulianbogdan can you confirm that this issue is fixed in version 5.2.0?

**Comment by vladiulianbogdan** [comment]
Yes. I can't reproduce the problem anymore.

**Comment by c0diq** [comment]
Can we close this now?
