### ISSUE TITLE
RxBluetoothService's scanningOutput won't output the repower-on devices 

### ISSUE THREAD

**Issue by aelam** [Polidea/RxBluetoothKit#317]
**Describe the bug**
I can get the device from scanningOutput, then I power off the device and power it on again. I can't scan it out from the scanningOuput anymore.

**To Reproduce**
1. One the ExampleApp
2. Click on Start Scanning, then I can get my device on the list
3. Power off my device and then power on, I won't get any scan output of my device 

**Expected behavior**

**Environment:**
 - Device: [e.g. iPhone6, Macbook Pro 2018]
 - OS: [e.g. iOS8.1, macOS 10.11]
 - Library version [e.g. 5.1.2]
 - Swift version [e.g. 4.1]

**Comment by Dong-Lin** [comment]
Add scanOptions will provide the fix for your problem
`                 let scanOptions = [CBCentralManagerScanOptionAllowDuplicatesKey : true]
                    self.centralManager.scanForPeripherals(withServices: nil, options:scanOptions)`

**Comment by aelam** [comment]
@Dong-Lin  Thanks! I'll try
