### ISSUE TITLE
.replay(1)?

### ISSUE THREAD

**Issue by AndrewSB** [Polidea/RxBluetoothKit#32]
Apologies for my unfamiliarity with rx operators, but can the use of `.replay(1)` on a stream be explained? 

From my use I believe it's convenient way to multicast something? So multiple subscribers get the same underlying sequence?

`.replay(1)` from my understanding would then make it so both the first and second subscriber of the observable would be subscribed to the same underlying stream.

Here for example: https://github.com/Polidea/RxBluetoothKit/blob/master/Source/RxCBCentralManager.swift#L127
What does that accomplish?

**Comment by literator** [comment]
Motivation for using `replay(1)` for `rx_state` is to give you very last state when you subscribe to this observable.

**Comment by Kacper20** [comment]
Closing issue for now - if you'll have any additional questions please feel free to reopen :)
