### ISSUE TITLE
Update library and example project to Swift 5

### ISSUE THREAD

**Issue by ptseng** [Polidea/RxBluetoothKit#321]
**Is your feature request related to a problem? Please describe.**
Desire to keep the library up to date.

**Describe the solution you'd like**
Update library and example project to Swift 5.

**Describe alternatives you've considered**
Doing it myself and submitting a pull request, as an alternative.

**Comment by minixT** [comment]
Hi @ptseng , I plan to do this by the end of the next week but hope it will be sooner.

**Comment by ptseng** [comment]
This PR looks like it's ready to go, can we please get a review?

https://github.com/Polidea/RxBluetoothKit/pull/322

**Comment by randomiser** [comment]
I'm keen to see this change also... Getting dependency issues when I try and use RxBluetooth with RxSwift / RxCocoa etc.

**Comment by nknotts** [comment]
It looks like this is merged, is there anyway to get a new release pushed to CocoaPods?

**Comment by minixT** [comment]
Released version 5.2.0 with Swift 5 support
