### ISSUE TITLE
Can I connect multi peripherals?

### ISSUE THREAD

**Issue by Sargis** [Polidea/RxBluetoothKit#326]

**Comment by dariuszseweryn** [comment]
Yes

**Comment by Sargis** [comment]
> Yes

How?

**Comment by dariuszseweryn** [comment]
Take a `Peripheral` and `.establishConnection()` to it 🎉

**Comment by Sargis** [comment]
> Take a `Peripheral` and `.establishConnection()` to it 🎉

Thanks a lot

**Comment by dariuszseweryn** [comment]
I hope this helps you.
If you need further assistance feel free to clearly state your needs.

Best Regards
