### ISSUE TITLE
Support to rxswift 5

### ISSUE THREAD

**Issue by GeorgeIvanov** [Polidea/RxBluetoothKit#336]

**Comment by dariuszseweryn** [comment]
Should be available shortly https://github.com/Polidea/RxBluetoothKit/pull/335

**Comment by dariuszseweryn** [comment]
@GeorgeIvanov What version of the lib do you use?

**Comment by SeRG1k17** [comment]
@dariuszseweryn 
Outdated dependency to RxSwift.
https://github.com/CocoaPods/Specs/blob/9069f2d21f66c1951be937c23e12b4532136c87b/Specs/4/9/6/RxBluetoothKit/5.2.0/RxBluetoothKit.podspec.json

**Comment by GeorgeIvanov** [comment]
The latest one, 5.2.0

**Comment by minixT** [comment]
Resolved in version 5.2.1
