### ISSUE TITLE
Peripheral Mode Support

### ISSUE THREAD

**Issue by denismars** [Polidea/RxBluetoothKit#34]
Are there any plans to support Peripheral Mode functionality such that we can advertise services?

i.e. the Rx counterpart of CBPeripheralManager.

**Comment by AndrewSB** [comment]
Mentioned this in #29 @denismars. It's in progress currently, using #30 to track it

**Comment by Kacper20** [comment]
Hi, @AndrewSB is implementing this. I will look at it tomorrow and check if i can help in some way ;) 
Closing for now
