### ISSUE TITLE
L2CAP method openL2CAPChannel should be available for OSX 10.14

### ISSUE THREAD

**Issue by c0diq** [Polidea/RxBluetoothKit#344]
**Describe the bug**
Rx Peripheral openL2CAPChannel method should be available on OSX 10.14 and above.

**Expected behavior**
The CoreBluetooth method is available on 10.14 but the RxBluetoothkit version is missing the proper @available annotation.

**Environment:**
 - OS: OSX 10.14
 - Library version 5.1.2
 - Swift version 5.0

**Comment by minixT** [comment]
Added to version 5.3.0
