### ISSUE TITLE
Memory leak when starting/stopping scanning

### ISSUE THREAD

**Issue by PhilippOtto89** [Polidea/RxBluetoothKit#36]
Hey there,

first of all thanks for making this awesome API. I really enjoy working with it. 

Unfortunately I receive memory leaks when turning scanning on and off. First I thought it´s a problem in my application but then I tried the provided example project and the problem also exists there.

Configuration:
iPhone 6 Plus
iOS 9.3.1
RxBluetoothKit 1.2.0

Steps:
1) Start RxBluetoothKit example project with simulator (Leaks)
2) Repeat turning scanning On/Off. (I switched it around every 5 secons)
3) Wait for leak to come

If you need any further info then don´t hesitate to ask. ;-)

Can you tell where this leak is coming from?

Thanks a lot!
Regards
Philipp

**Comment by Kacper20** [comment]
Hi there,
Thank you very much for reporting it - it's really helpful.
I'm taking a look at it and we'll release fix in Monday - we need to investigate it and make sure it doesn't happen anywhere else. 

Regards,

Kacper

**Comment by Kacper20** [comment]
Hello, we've investigated it and have found the issue.
This will be fixed by #40.

**Comment by Kacper20** [comment]
Hi,
1.2.2 with this fix is now available. Please let us know if it works for you :)  

Thanks!
