### ISSUE TITLE
IsScanning property

### ISSUE THREAD

**Issue by lfongaroScp** [Polidea/RxBluetoothKit#365]
**Is your feature request related to a problem? Please describe.**
I need to know if the bluetooth is in scan mode, but I do not found a way

**Describe the solution you'd like**
A simple property (and maybe a observable) which I can check if the there is a scan in progress

**Comment by dariuszseweryn** [comment]
Hello, you can simply track if the app has started scanning, no?

**Comment by lfongaroScp** [comment]
I appreciate your work and I thank for the effort you put in build this library, but _obviously_ I can track this, but a library of this kind should track his own state internally (active, connected, scan etc).
