### ISSUE TITLE
listenOnRestoredState() should be Public

### ISSUE THREAD

**Issue by mane87** [Polidea/RxBluetoothKit#38]
Hi,
finaly i am going to give staterestoration a try.

In you readme you write:
 **Later, just make sure to subscribe to listenOnRestoredState observable, and inspect RestoredState instance, which consists any useful info about restored state.**

But listenOnRestoredState() is private. Shouldn't it be public?

Cheers

**Comment by Kacper20** [comment]
Hi,
Yea, that's right. That's our mistake. Will make it public in tomorrow's release. 
Thanks!

**Comment by mane87** [comment]
Oh, cool!
Wasn't sure if I am overlooking something, otherwise I would have made a pull request.
Thank you very much for your fast answer!

**Comment by mane87** [comment]
Hi,
any news for the update?

Should i make a pull request for the change?

Thanks again

**Comment by Kacper20** [comment]
Hi there,

Now the version with fix is available on Github. It's 1.2.1.
Please wait a bit for availability in Cocoapods(pushed to trunk already).

Have a nice day and let us know in case of any problems :-) Thanks!

**Comment by mane87** [comment]
Thanks.
I'll give it a try and let you know if there are any problems.

You guys are awesome!!! 👍🏼👍🏼👍🏼

**Comment by Kacper20** [comment]
Closing for now. If anything will come up - just reopen it or(the better) make another issue.
