### ISSUE TITLE
RXBluetoothKit get notified on peripheral disconnect

### ISSUE THREAD

**Issue by JanBrinker** [Polidea/RxBluetoothKit#41]
Hi,
I'm currently trying out the RxBluetoothKit for a project and I want my app to connect to several peripherals simultaneously. Now I'd like to be notified in some way if one peripheral drops out in some way or closes the connection.

I could actively loop over the list of connected peripherals periodically and read out the **isConnected** property, but this seems a bit unclean to me. Is there a more elegant way to achieve this and get notified directly?

Thanks in advance :)

**Comment by literator** [comment]
Hi,

Did you try subscribing to rx_state subject property on Peripheral?

Maciej Oczko
Polidea | Head of Engineering

**Comment by JanBrinker** [comment]
Will try that and tell you how it went or if I need some more info, I still need to wrap my head around Rx.
But thanks for the tip :)

**Comment by Kacper20** [comment]
Hello,

You could also try to subscribe to `monitorPeripheralDisconnection` on `BluetoothManager` method. All you need to do is to have reference to `Peripheral` instance.
We have this exact thing in our `Example` app. Maybe it's worth for you to take a look :-)

**Comment by Kacper20** [comment]
Closing issue for now - if you'll have any additional questions please feel free to reopen :)
