### ISSUE TITLE
Cannot specialize non-generic type 'Observable<Element>'

### ISSUE THREAD

**Issue by avinashamanjha251** [Polidea/RxBluetoothKit#422]
Hi Dev team,
I just install RXBluetoothkit with Xcode 15 and start getting "Cannot specialize non-generic type 'Observable<Element>'".

![Screenshot 2023-09-27 at 12 17 37 PM](https://github.com/Polidea/RxBluetoothKit/assets/27722634/2f79b17a-9424-4f29-9c71-a628e0142a1d)

Thanks in advance.

**Comment by jberkhei** [comment]
You can get it to compile by updating it to this, however you will then run into RXSwift 6 issues.

return Observable.empty()

**Comment by torhenningegenes** [comment]
I am having the same problem. Would love to hear if anyone has gotten around this including the RXSwift 6 issues.

**Comment by jberkhei** [comment]
People have forked this and fixed it.  My work arounds.

pod 'RxSwift', '~> 6.0'
pod 'RxCocoa', '~> 6.0'
pod 'RxBluetoothKit', :git => 'https://github.com/jberkhei/RxBluetoothKit.git', :branch => 'master'
pod 'RxMKMapView', :git => 'https://github.com/jberkhei/RxMKMapView.git', :branch => 'master'
pod 'RxRealm', :git => 'https://github.com/jberkhei/RxRealm.git', :branch => 'main'

**Comment by torhenningegenes** [comment]
Thank you for answering so quickly. Didn't run into any issues with RXSwift when I removed the `Element` type. At least not yet. 🙂

**Comment by avinashamanjha251** [comment]
Here's my side update. 

![Screenshot 2023-10-03 at 7 11 03 PM](https://github.com/Polidea/RxBluetoothKit/assets/27722634/fe9458dc-00b5-443e-8651-589815658d79)
