### ISSUE TITLE
Migration to Swift 2.3 

### ISSUE THREAD

**Issue by literator** [Polidea/RxBluetoothKit#47]
- [ ] Adapt to changes in iOS 10 frameworks.
- [ ] Update documentation
- [ ] Use uniform code formatting conventions.
- [ ] Make tests pass on iOS 10.
- [ ] Check if compatibility is preserved when migrating from iOS 8.
- [ ] Fix warnings regarding tests
- [ ] Support Swift Package Manager

**Comment by Kacper20** [comment]
Everything is implemented in `2.0.0` version of the library besides supporting Swift Package manager. For this i opened another issue #56.
