### ISSUE TITLE
Mark rx_state on peripheral as deprecated

### ISSUE THREAD

**Issue by literator** [Polidea/RxBluetoothKit#48]
This features doesn't work anyways, so it has to be refactored.

- [ ] Mark `rx_state` as deprecated
- [ ] Remove RxCocoa dependency
- [ ] Reimplement `rx_isConntected`

**Comment by Kacper20** [comment]
Everything is implemented in `2.0.0` version of the library with one change: `rx_state` on `Peripheral` was removed from library, because we were not able to provide intended behavior.
