### ISSUE TITLE
RxSwift dependency version

### ISSUE THREAD

**Issue by michaello** [Polidea/RxBluetoothKit#58]
I guess this should be defined as '2.6.0'. Otherwise we'll be getting an error:

[!] Unable to satisfy the following requirements:
- RxSwift (= 2.6.0) required by Podfile
- RxSwift (= 2.6.0) required by Podfile.lock
- RxSwift (~> 2.5) required by RxCocoa (2.6.0)
- RxSwift (= 2.6) required by RxBluetoothKit (2.0.0)

**Comment by Kacper20** [comment]
Hi,
Thanks for letting us know.
This is fixed in `2.0.1`. 

Have a nice day
