### ISSUE TITLE
Example project not building

### ISSUE THREAD

**Issue by mkulikov** [Polidea/RxBluetoothKit#62]
Example project not building on my XCode 8.0
Here is 52 Swift Compiler Error in RxSwift Pod

**Comment by Kacper20** [comment]
Which version of Cocoapods you're running on?

**Comment by mkulikov** [comment]
1.0.1

**Comment by Kacper20** [comment]
And which version of RxSwift is installed when you're running `pod install`? Could you remove Podfile.lock and perform `pod install` once again?

**Comment by mkulikov** [comment]
2.6.0

**Comment by Kacper20** [comment]
Are you using Swift 3.0? Or Swift 2.3?

**Comment by mkulikov** [comment]
Swift 3.0

**Comment by Kacper20** [comment]
It should download RxSwift in 3.0-beta version. Have you tried removing Podfile.lock or run `pod update?`. :)

**Comment by mkulikov** [comment]
After update build completed. Thank you!

**Comment by Kacper20** [comment]
Glad it worked :-)
