### ISSUE TITLE
Support for CBPeripheralDelegate

### ISSUE THREAD

**Issue by Kacper20** [Polidea/RxBluetoothKit#66]
To cover entirely CoreBluetooth API we need to support part of it that makes possible to use Apple device as a peripheral. 
I'm not entirely sure how it'll affect the other parts of API - since in iOS 10 `CBPeripheralManager` and `CBCentralManager` are inheriting from `CBManager` subclass it can be a good idea to make such move in our library too. This would probably mean renaming `BluetoothManager`, and introduce breaking change. 

Need to perform further investigations of possibilities to make it as smooth as possible.

**Comment by mkulikov** [comment]
it will be great!

**Comment by garsdle** [comment]
How is this coming along? I'm actually using both CBCentralManager and CBPeripheralManager in a pet project and was going to make the jump to RxBluetoothKit. Having both would be amazing. I'm willing to help as well if there is anything I can do.

**Comment by Kacper20** [comment]
I am closing this issue — will create a new one soon with detailed design.
