### ISSUE TITLE
How can I stop scanning peripheral?

### ISSUE THREAD

**Issue by alyadan** [Polidea/RxBluetoothKit#73]
When I use BluetoothManager to scanning peripheral ,I can not find a way to stop scanning

**Comment by Kacper20** [comment]
Hi,

When you subscribe on scanning operation, you have access to disposable instance. When you're ready to stop scan just call `dispose()` on received disposable.
Does that answers your question?

Kacper

**Comment by alyadan** [comment]
Yes, I agree with you ,but it dosen't work, mabye there are some wrong whith my code.  thanks

**Comment by alyadan** [comment]
yes, it's working, thanks a lot

**Comment by Kacper20** [comment]
That's great :)
In case of any further problems - please feel free to ask.
