### ISSUE TITLE
Because bluetooth transmission data of each time is limited, if separated, can have what good example?

### ISSUE THREAD

**Issue by LiuSky** [Polidea/RxBluetoothKit#76]
@Kacper20   Every single to the maximum length of data written to the printer is limited, I want to know if I have a data is very large, many times how to write

**Comment by Kacper20** [comment]
Hi there,
Basically you need to split your data into the packets.
The best way would be to have a function which splits it and returns an Array of NSData values.
Then, you need to perform sequentional write. Code depends on the way your characteristic is working on(do you need to wait on the notification, or just perform writes with acknowledge?).
Here you have example of very similiar issue(seq writes) and possible solution:
https://github.com/Polidea/RxBluetoothKit/issues/75

If case you need more help - please feel free to ask.

Kacper

**Comment by LiuSky** [comment]
All right.I go to take a look at first.thank you @Kacper20

**Comment by LiuSky** [comment]
<img width="911" alt="2016-11-16 9 17 47" src="https://cloud.githubusercontent.com/assets/3087745/20348765/2a3b61e4-ac42-11e6-9a31-980fe273aa9a.png">
I found that the print soon, or accidentally messing with the order.This is what circumstance @Kacper20
