### ISSUE TITLE
Support for discovering multiple services & characteristics with the same UUIDs

### ISSUE THREAD

**Issue by Kacper20** [Polidea/RxBluetoothKit#82]
This is thing that we're not currently supporting, and it's major issue for now. It would require changing API, so it will land in 4.0 release.
Design of this implementation is currently in progress.

**Comment by brycejacobs** [comment]
What's the holdup of PR #89 ? It doesn't break the surface API from what I can see.

**Comment by abeintopalo** [comment]
I guess this can be closed since PR #109 was merged.
