### ISSUE TITLE
All examples are not valid for RxSwift 3.0 due to subscribeNext deprecation

### ISSUE THREAD

**Issue by alfishe** [Polidea/RxBluetoothKit#85]
Seems help materials need to be forked and adapted separately. Otherwise there is initial bump for newcomers

**Comment by Kacper20** [comment]
Hi there,

That's true. We forgot about changing `subscribeNext` according to `RxSwift 3.0`. Will fix it right away in `README`.  

Thanks very much for pointing this out.

Kacper

**Comment by Kacper20** [comment]
It's in master right now.

Thanks again,
