### ISSUE TITLE
not seing the same device list as settings app

### ISSUE THREAD

**Issue by berkankisaoglu** [Polidea/RxBluetoothKit#95]
Hey guys, *quick question*. 

I'm running the Example project here. 
Starting a scan. 
After couple of minutes, I only see my mac's bluetooth. 

The problem is when I go to the settings -> bluetooth and do a scan there, I was able to discover my bluetooth headphones and bluetooth speakers as well. 
Why are the lists are so different? Is that a restriction on iOS side?

**Comment by Kacper20** [comment]
Hello,

This shouldn't be a case.
Are speakers and headphones BLE devices?
Are they disconnected from your Mac while performing scan while Example app?

Regards

**Comment by berkankisaoglu** [comment]
My bad. So sorry to bother you. 
You were right, they were Bluetooth 3.0 devices.

**Comment by Kacper20** [comment]
Not a problem :)
Have a nice day :)
