### ISSUE TITLE
How to continuously read a connected peripheral's RSSI?

### ISSUE THREAD

**Issue by bananapps** [Polidea/RxBluetoothKit#96]
Hi everyone,
I was wondering how do you continuously read the RSSI for a connected peripheral? I want to know what the updated RSSI value is at all times so I can keep track of a peripheral's signal strength.
Thank you.

**Comment by bananapps** [comment]
I figured it out!
`fileprivate func triggerValueRead(for characteristic: Characteristic) {
        characteristic.setNotificationAndMonitorUpdates()
            .subscribe(onNext: {
                if self.connectedPeripheral != nil { // connectedPeripheral is the peripheral I connected to
                    self.connectedPeripheral?.readRSSI().flatMap { Observable.from($0) }
                        .subscribe(onNext: {
                            print($0.1) // rssi value
                        })
                }
       }
}
`

**Comment by Kacper20** [comment]
Hello @bananapps 
That's right.
For chaining of operations you could also use `flatMap` instead of `subscribe` if you're not doing anything else.
Also, you could take peripheral from `characteristic.service.peripheral` instead.

Glad it works for you - please write in case of any questions.

Kacper

**Comment by tnmendes** [comment]
How can continuously read a peripheral's RSSI without being connected?
Or how can i continuously receive the same peripheral using this method because with this code it just received once?

```
scanningDisposable = manager.rx_state
      //.filter { $0 == .poweredOn }
      .timeout(4.0, scheduler: scheduler)
      .take(1)
      .flatMap { _ in self.manager.scanForPeripherals(withServices: nil, options:nil) }
      .subscribeOn(MainScheduler.instance)
      .subscribe(onNext: {
        self.addNewScannedPeripheral($0)
      }, onError: { error in
        print("Manager rx_state: ",error)
      })
```

**Comment by moogle19** [comment]
@tnmendes 
You need to allow duplicates during scanning.
Take a look at https://developer.apple.com/reference/corebluetooth/cbcentralmanager/peripheral_scanning_options

**Comment by tnmendes** [comment]
Thanks @moogle19 ...that was the solution 👍

**Comment by Kacper20** [comment]
Thanks @moogle19 :)
